### ISSUE TITLE
"None" Speech Bubble in Courtroom

### ISSUE THREAD

**Issue by Hanif2108** [objection-lol/website#196] opened 2020-12-14 16:30 UTC
Hey, uh, there's this one bug that I found in the courtroom. Take a look at these 2 picture

▪︎ Preset Characters
![20201214_232602.jpg](https://user-images.githubusercontent.com/75522729/102107046-dfa8d400-3e63-11eb-8ec3-eba9a4fd9c60.jpg)
▪︎ Custom Characters
![20201214_232623.jpg](https://user-images.githubusercontent.com/75522729/102107098-eb949600-3e63-11eb-9821-4f5371e8b146.jpg)

As you can see, the first picture shows that the "None" speech bubble exist, while the other don't. If the none button doesnt exist, then you can't get rid the speech bubble. Is there a way to fix this?

**Comment by maxdevgithub** [comment] 2020-12-14 16:50
Duplicate of #195

**Closed** 2020-12-14 20:07 UTC
